# NumPy Tutorial

## Import Numpy Module

In [1]:
import numpy as np

## Check Version of NumPy
### 1. __version__ 

In [2]:
print(np.__version__)

1.18.1


## Create ndarray
### 1. array()

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# Zero dimensional array
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [6]:
# One dimensional array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# Two dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# Three dimensional array
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
# Higher dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


## Check dimension of any array
### 1. ndim

In [10]:
print(arr.ndim)

5


## Indexing of an array

In [11]:
arr = np.array([1,2,3,4,5,6])

for i in range(0,len(arr)):
    print(arr[i])

1
2
3
4
5
6


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
# Normal List Indexing
print(arr[0][1])
# Matrix Indexing
print(arr[0,1])

[[1 2 3]
 [4 5 6]]
2
2


In [13]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


## Slicing of an array

In [14]:
arr = np.array([1,2,3,4,5,6])

# [Start:end]
print(arr[1:5])
print(arr[1:len(arr)])
print(arr[0:])
print(arr[:len(arr)])

# [Start:end:step]
print(arr[1:len(arr):2])
print(arr[::2])

[2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[2 4 6]
[1 3 5]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr)
print()
print(arr[1, 1:4])
print()
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[7 8 9]

[[2 3 4]
 [7 8 9]]


## Datatypes in numpy
### 1. dtype

In [16]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

arr = np.array([1, 2, 3, 4])

# Check datatype of an array
print(arr.dtype)

int32


In [17]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [18]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Use of astype() function

In [20]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [21]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## Copy and View

In [22]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Check array contain own data or not

In [24]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(arr.base) # It will give none because they contain own data
print(x.base) # It will give none because they contain own data
print(y.base)

None
None
[1 2 3 4 5]


## Want to check number of rows and columns in an array
### 1. shape

In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## Want to change number of rows and columns as your desire
### 1. reshape()

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# We can also convert 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Iteration in Numpy
### 1. nditer()
### 2. ndenumerate()

In [31]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [34]:
# Want to iterante an array and want both index and value----------------------------------------------->
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


## Join number of array
### 1. concatenate()
### 2. stack()
### 3. hstack()
### 4. vstack()
### 5. dstack()

In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

# Use of concatenate
arr = np.concatenate((arr1, arr2, arr3))

print(arr)

[1 2 3 4 5 6 7 8 9]


In [41]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
print()

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# Use of stack
arr = np.stack((arr1, arr2), axis=1)

print(arr)
print()

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# Use of hstack
arr = np.hstack((arr1, arr2))

print(arr)
print()

# Use of vstack
arr = np.vstack((arr1, arr2))

print(arr)
print()

# Use of dstack
arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


## Split an array
### 1. array_split()
### 2. hsplit()
### 3. vsplit()
### 4. dsplit()

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [53]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(arr)
print()
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Use of hstack
newarr = np.hsplit(arr, 3)

print(newarr)
print()

# Use of vstack
newarr = np.vsplit(arr, 3)

print(newarr)
print()

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]



## Searching arrays
### 1. where()
### 2. searchsorted()

In [62]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Use of Where()
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [65]:
arr = np.array([6, 7, 8, 9, 7])

# Use of searchsorted()
x = np.searchsorted(arr, 7)

print(x)

1


In [68]:
arr = np.array([6, 7, 8, 9, 7])

x = np.searchsorted(arr, 7, side='right') # It will not follow indexing

print(x)
print()

x = np.searchsorted(arr, 7, side='left')

print(x)

2

1


In [71]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sort an array

In [72]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [73]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [74]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filter an array

In [77]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

# If the value at an index is True that element is contained in the filtered array, if the value at that index is False that
# element is excluded from the filtered array.
newarr = arr[x]

print(newarr)

[41 43]


In [78]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Intro of Generate random number
### 1. random.randint()
### 2. random.rand()
### 3. random.choice()

In [81]:
# Use of randint()
x = np.random.randint(100)

print(x)

86


In [85]:
from numpy import random

# Use of rand()
x = random.rand()

print(x)
print()

x = random.rand(5)

print(x)

0.3538131300384103

[0.86065439 0.13433952 0.88045836 0.83024614 0.5129731 ]


In [84]:
x=random.randint(100, size=(5))

print(x)
print()

x = random.randint(100, size=(3, 5))

print(x)

[51 33 76 85 77]

[[46 22 53 61 23]
 [45 20 61 25 45]
 [68 74 36 55 68]]


In [86]:
# Use of choice()
x = random.choice([3, 5, 7, 9])

print(x)

7


In [87]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 9 3 7 3]
 [3 9 3 3 3]
 [9 3 3 3 7]]


## Intro of Numpy ufunc
### 1. zip()
### 2. add()

In [88]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [89]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]
